baseurl = "https://popandgo.gr/"
canonifyURLs = true
languageCode = "el-GR"
languageLang = "el"
title = "Pop & Go"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[permalinks]
post = "/post/:slug/"

[params]
homeTitle = "Pop & Go - σινεμά και ταινίες στην Ελλάδα"
description = "Ανακάλυψε τι παίζει στα κοντινά σινεμά με το Pop & Go. Βρες όλες τις ταίνιες, προβολές, και τα σινεμά κοντά σου. Η απόλυτη εφαρμογή για τους λάτρεις του σινεμά στην Ελλάδα."
keywords = "movies Greece, cinema Athens, theater showtimes, movie app Greece, nearby theaters, ταινίες Ελλάδα, σινεμά Αθήνα, προβολές ταινιών"
images = ["img/mascot-full.png"]

# Social Links
instagram = "https://www.instagram.com/popandgo.gr"
tiktok = "https://www.tiktok.com/@popandgo.gr"
facebook = "https://www.facebook.com/popandgo.gr"

# App Store Links
appStoreUrl = "https://apps.apple.com/app/6748235605"
playStoreUrl = "https://play.google.com/store/apps/details?id=me.lagbug.popandgo"
