backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog Posts" # Used in the UI
    folder: "site/content/post" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    media_folder: "" # Store images in the same folder as the post
    public_folder: "" # Reference images without a path prefix
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description (SEO)", name: "description", widget: "text"}
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title (Greek)", name: "titleGr", widget: "string"}
              - {label: "Title (English)", name: "titleEn", widget: "string"}
              - {label: "Subtitle (Greek)", name: "subtitleGr", widget: "text"}
              - {label: "Subtitle (English)", name: "subtitleEn", widget: "text"}
              - {label: "Playful Text (Greek)", name: "playfulGr", widget: "string"}
              - {label: "Playful Text (English)", name: "playfulEn", widget: "string"}
          - label: "How It Works Section"
            name: "howItWorks"
            widget: "object"
            fields:
              - {label: "Title (Greek)", name: "titleGr", widget: "string"}
              - {label: "Title (English)", name: "titleEn", widget: "string"}
              - {label: "Subtitle (Greek)", name: "subtitleGr", widget: "string"}
              - {label: "Subtitle (English)", name: "subtitleEn", widget: "string"}
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - {label: "Number", name: "number", widget: "string"}
                  - {label: "Title (Greek)", name: "titleGr", widget: "string"}
                  - {label: "Title (English)", name: "titleEn", widget: "string"}
                  - {label: "Description (Greek)", name: "descriptionGr", widget: "text"}
                  - {label: "Description (English)", name: "descriptionEn", widget: "text"}
  
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/hugo.toml"
        label: "Site Configuration"
        name: "config"
        editor:
          preview: false
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Language Code", name: "languageCode", widget: "string", default: "el-GR"}
          - label: "Parameters"
            name: "params"
            widget: "object"
            fields:
              - {label: "Site Description", name: "description", widget: "text"}
              - {label: "Keywords (comma separated)", name: "keywords", widget: "string"}
              - {label: "Instagram URL", name: "instagram", widget: "string"}
              - {label: "TikTok URL", name: "tiktok", widget: "string"}
              - {label: "App Store URL", name: "appStoreUrl", widget: "string"}
              - {label: "Play Store URL", name: "playStoreUrl", widget: "string"}
              - label: "Open Graph Images"
                name: "images"
                widget: "list"
                field: {label: "Image", name: "image", widget: "string", default: "img/mascot-full.png"}
